apiVersion: v1
kind: DeploymentConfig
metadata:
  name: oc
  labels:
    run: oc
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    run: oc
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oc
    spec:
      containers:
        -
          name: oc
          image: 'docker.io/openshiftdemos/oc:1.4.1-1'
          command:
            - bash
            - '-c'
            - 'while true; do sleep 60; done'
          resources:
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: